fetch("https://soldasul.sankhyacloud.com.br/mge/service.sbr?serviceName=DatasetSP.loadRecords&counter=45&application=ImportacaoXMLNotas&outputType=json&preventTransform=false&mgeSession=GJOuOJyZcqkSlfe8W5JjZqaznyykZa1eXRO8paDK&resourceID=br.com.sankhya.cac.ImportacaoXMLNota&globalID=BEC2186AA7E4226DF15416CC061ACDF4&allowConcurrentCalls=true&vss=1", {
    "headers": {
      "accept": "application/json, text/plain, */*",
      "accept-language": "en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7",
      "content-type": "application/json; charset=UTF-8",
      "sec-ch-ua": "\"Not(A:Brand\";v=\"99\", \"Brave\";v=\"133\", \"Chromium\";v=\"133\"",
      "sec-ch-ua-mobile": "?0",
      "sec-ch-ua-platform": "\"Linux\"",
      "sec-fetch-dest": "empty",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "sec-gpc": "1",
      "cookie": `JSESSIONID=GJOuOJyZcqkSlfe8W5JjZqaznyykZa1eXRO8paDK.sankhya-w-56868f8df4-m9p9t; userIDLogado=12; recuperaTela=br.com.sankhya.cac.ImportacaoXMLNota%3Bbr.com.sankhya.mgecom.mov.PortalCompras%3B; isB2B=N; __zlcmid=1QOnQFpSB9ixto1; _gid=GA1.3.288832520.1742815365; _ga_ZQK18B28LT=GS1.3.1742838658.76.0.1742838658.0.0.0; ph_phc_tvyNWeDrAfQAbDMQoGCObKf3yO3rSpTj9aWKexlBRKI_posthog=%7B%22distinct_id%22%3A%2212-ERIC-03e10d9b0ee70fa809824cbd20dd50c04aa52ce905%22%2C%22%24sesid%22%3A%5B1742838693739%2C%220195c947-e994-789b-a4ff-0dd065c20fb5%22%2C1742838688148%5D%2C%22%24epp%22%3Atrue%2C%22%24initial_person_info%22%3A%7B%22r%22%3A%22https%3A%2F%2Fsoldasul.sankhyacloud.com.br%2Fmge%2Fsystem.jsp%22%2C%22u%22%3A%22https%3A%2F%2Fsoldasul.sankhyacloud.com.br%2Fmgefin-bff%2FMovimentacaoFinanceira.xhtml5%3FmgeSession%3D67yY75trXM4WrojFWzoO2Rmv156D0voAqsYD2AAA%26resourceID%3Dbr.com.sankhya.fin.cad.movimentacaoFinanceira%26html5ScreenChoice%3DS%26changeLayout%3DS%26isFirstAccess%3DN%26betaApp%3Dfalse%26%26legacyLayoutInUse%3DV2%26V3%3Dtrue%26usingV3%3DS%26changeLayoutV3%3DS%26firstLoadConv%3DS%26defaultModuleName%3Dmgefin%26V3ModuleName%3Dmgefin-bff%23%22%7D%7D;`,
      "Referer": `https://soldasul.sankhyacloud.com.br/mgecom/ImportacaoXMLNotas.xhtml5?mgeSession=GJOuOJyZcqkSlfe8W5JjZqaznyykZa1eXRO8paDK&resourceID=br.com.sankhya.cac.ImportacaoXMLNota&html5ScreenChoice=S&changeLayout=S&isFirstAccess=N&betaApp=false&newLayoutSupChoice=S`,
      "Referrer-Policy": "strict-origin-when-cross-origin"
    },
    "body": {
        "serviceName":"DatasetSP.loadRecords",
        "requestBody":{
            "dataSetID":"001",
            "entityName":"ImportacaoXMLNotas",
            "standAlone":false,
            "orderByExpression":"NUARQUIVO",
            "fields":[
                "DIASEMISSAOCALC",
                "CODTIPOPER",
                "TipoOperacao.DESCROPER",
                "CODEMP",
                "Empresa.NOMEFANTASIA",
                "CODPARC",
                "Parceiro.NOMEPARC",
                "CODVEND",
                "Vendedor.APELIDO",
                "SITUACAOMDE",
                "IMPORTADOMDE",
                "SITUACAONFE",
                "TEMXML",
                "VLRNOTA",
                "DHEMISS",
                "TIPO",
                "CONFIG",
                "DHPROCESS",
                "XML",
                "CODUSUPROC",
                "Usuario2.NOMEUSU",
                "CODUSUIMP",
                "Usuario.NOMEUSU",
                "DHIMPORT",
                "NUMNOTA",
                "NUARQUIVO",
                "CHAVEACESSO",
                "DETALHESIMPORTACAO",
                "NOMEARQUIVO",
                "STATUS",
                "STATUSWMS",
                "NUNOTA",
                "NUFIN",
                "TIPIMPCTE",
                "DTVENC",
                "CODPARCCOLETACTE",
                "ParceiroColeta.NOMEPARC",
                "CODPARCENTREGACTE",
                "ParceiroEntrega.NOMEPARC",
                "TIPONFE",
                "SITUACAOCTE",
                "PAPELCTE",
                "ULTEVEDFE",
                "OBSERVACAODFE",
                "DOCSREF",
                "TIPOCTE",
                "TOMADORCTE",
                "TIPOMANIFDFE",
                "SERIEDOC",
                "NATUREZAOPER",
                "CODPARCDEST",
                "ParceiroDestinatario.NOMEPARC",
                "DTAUTORIZACAO",
                "PLACAVEIC",
                "CNPJTRANSP",
                "CODPARCTRANSP",
                "ParceiroTransportadora.NOMEPARC",
                "CNPJPARC",
                "CNPJREMET",
                "CODPARCREMET",
                "ParceiroRemetenteCte.NOMEPARC",
                "CNPJDEST",
                "CNPJEXPED",
                "CODPARCEXPED",
                "ParceiroExpedidor.NOMEPARC",
                "CNPJRECEB",
                "CODPARCRECEB",
                "ParceiroRecebedor.NOMEPARC",
                "ENTSAINFE",
                "CFOPXML",
                "DTCONFIRMACAO",
                "XNOMEEMIT",
                "XNOMEDEST",
                "XNOMETRANSP",
                "XNOMETOMA",
                "NUMCOTACAO",
                "CODCENCUS",
                "CentroResultado.DESCRCENCUS",
                "DHPROCAG",
                "CODNAT",
                "Natureza.DESCRNAT",
                "CODPROJ",
                "CODTIPVENDA",
                "TipoNegociacao.DESCRTIPVENDA",
                "AD_NOME",
                "Parceiro.NOMEPARC",
                "Parceiro.CODPARCMATRIZ",
                "Empresa.CGC",
                "Parceiro.ParceiroMatriz.NOMEPARC"
            ],
            "tryJoinedFields":true,
            "parallelLoader":true,
            "crudListener":"br.com.sankhya.modelcore.comercial.ImportacaoXmlNotasCrudListener",
            "criteria":{
                "expression":"(onlydate(this.DHEMISS) >= ?)",
                "parameters": [
                    {
                        "type":"S",
                        "value":"01/03/2025"
                    }
                ]
            },
            "txProperties": {
                "ConfigToSaveAt:br.com.sankhya.cac.ImportacaoXMLNota.personalizedfilter.DynamicFilterAccordion":"eyJwcm9nQ3JpdGVyaWEiOltdfQ=="
            },
            "ignoreListenerMethods":"",
            "useDefaultRowsLimit":false}},
    "method": "POST"
  }).then(data => {
    return data.json()
  }).then(res => {
    console.log(res);
    
  });